-- Initial schema for wedding invitation SPA
-- Tables: wedding_config (singleton), guest_group, guest, admin_users, email_outbox

set check_function_bodies = off;

-- Configuracion global del evento (singleton row id=1)
create table if not exists public.wedding_config (
  id integer primary key generated by default as identity,
  wedding_date timestamptz,
  rsvp_deadline timestamptz,
  rsvp_open boolean not null default true,
  published_at timestamptz not null default now(),
  ceremony_location_name text,
  ceremony_location_address text,
  ceremony_location_maps_url text,
  ceremony_time time,
  reception_location_name text,
  reception_location_address text,
  reception_location_maps_url text,
  reception_time time,
  dress_code text,
  registry_links jsonb default '[]'::jsonb,
  notes text,
  welcome_message text,
  relationship_start_year integer,
  couple_photos jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint single_row check (id = 1)
);

-- Grupo de invitacion (familia, pareja, etc)
create table if not exists public.guest_group (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  display_name text not null,
  relationship text,
  max_attendees integer not null check (max_attendees > 0),
  message text,
  songs jsonb not null default '[]'::jsonb,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_guest_group_token on public.guest_group(token);
create index if not exists idx_guest_group_responded on public.guest_group(responded_at);

-- Persona dentro de un grupo (primario o acompanante)
create table if not exists public.guest (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.guest_group(id) on delete cascade,
  full_name text not null,
  is_primary boolean not null default false,
  attending boolean,
  dietary_restrictions text,
  source text not null default 'guest' check (source in ('guest', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_guest_group_id on public.guest(group_id);
create unique index if not exists idx_guest_one_primary_per_group
  on public.guest(group_id) where is_primary = true;

-- Whitelist de emails admin
create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default now()
);

-- Cola de emails con idempotencia y retry.
-- dedupe_bucket es una columna normal con DEFAULT (no GENERATED) porque Postgres
-- admite expresiones STABLE en default pero no en generated. El bucket de 5 min
-- garantiza que dos RSVPs del mismo grupo en menos de 5 min generen UNIQUE conflict.
create table if not exists public.email_outbox (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.guest_group(id) on delete cascade,
  payload jsonb not null,
  sent_at timestamptz,
  attempts integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  dedupe_bucket bigint not null default (floor(extract(epoch from clock_timestamp()) / 300))::bigint
);

create unique index if not exists idx_email_outbox_dedupe
  on public.email_outbox (group_id, dedupe_bucket);

create index if not exists idx_email_outbox_pending
  on public.email_outbox (created_at)
  where sent_at is null and attempts < 3;

-- Trigger generico de updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_wedding_config_updated_at
  before update on public.wedding_config
  for each row execute function public.set_updated_at();

create trigger trg_guest_group_updated_at
  before update on public.guest_group
  for each row execute function public.set_updated_at();

create trigger trg_guest_updated_at
  before update on public.guest
  for each row execute function public.set_updated_at();
