-- =========================================================================
-- COMBINED MIGRATIONS — wedding-invitation
-- =========================================================================
-- Pegar este archivo entero en Supabase Dashboard → SQL Editor → Run.
-- Ejecuta las 5 migrations en orden dentro de una sola transaccion.
-- Idempotente: usa "if not exists" / "create or replace" donde aplica.
-- =========================================================================

begin;

-- =========================================================================
-- 20260509000000_initial_schema.sql
-- =========================================================================
set check_function_bodies = off;

create table if not exists public.wedding_config (
  id integer primary key generated by default as identity,
  wedding_date timestamptz,
  rsvp_deadline timestamptz,
  rsvp_open boolean not null default true,
  published_at timestamptz not null default now(),
  ceremony_location_name text,
  ceremony_location_address text,
  ceremony_location_maps_url text,
  ceremony_time time,
  reception_location_name text,
  reception_location_address text,
  reception_location_maps_url text,
  reception_time time,
  dress_code text,
  registry_links jsonb default '[]'::jsonb,
  notes text,
  welcome_message text,
  relationship_start_year integer,
  couple_photos jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint single_row check (id = 1)
);

create table if not exists public.guest_group (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  display_name text not null,
  relationship text,
  max_attendees integer not null check (max_attendees > 0),
  message text,
  songs jsonb not null default '[]'::jsonb,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_guest_group_token on public.guest_group(token);
create index if not exists idx_guest_group_responded on public.guest_group(responded_at);

create table if not exists public.guest (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.guest_group(id) on delete cascade,
  full_name text not null,
  is_primary boolean not null default false,
  attending boolean,
  dietary_restrictions text,
  source text not null default 'guest' check (source in ('guest', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_guest_group_id on public.guest(group_id);
create unique index if not exists idx_guest_one_primary_per_group
  on public.guest(group_id) where is_primary = true;

create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.email_outbox (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.guest_group(id) on delete cascade,
  payload jsonb not null,
  sent_at timestamptz,
  attempts integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  dedupe_bucket bigint not null default (floor(extract(epoch from clock_timestamp()) / 300))::bigint
);

create unique index if not exists idx_email_outbox_dedupe
  on public.email_outbox (group_id, dedupe_bucket);

create index if not exists idx_email_outbox_pending
  on public.email_outbox (created_at)
  where sent_at is null and attempts < 3;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_wedding_config_updated_at on public.wedding_config;
create trigger trg_wedding_config_updated_at
  before update on public.wedding_config
  for each row execute function public.set_updated_at();

drop trigger if exists trg_guest_group_updated_at on public.guest_group;
create trigger trg_guest_group_updated_at
  before update on public.guest_group
  for each row execute function public.set_updated_at();

drop trigger if exists trg_guest_updated_at on public.guest;
create trigger trg_guest_updated_at
  before update on public.guest
  for each row execute function public.set_updated_at();

-- =========================================================================
-- 20260509000001_rls.sql
-- =========================================================================
alter table public.wedding_config enable row level security;
alter table public.guest_group enable row level security;
alter table public.guest enable row level security;
alter table public.admin_users enable row level security;
alter table public.email_outbox enable row level security;

-- =========================================================================
-- 20260509000002_token_generator.sql
-- =========================================================================
create or replace function public.generate_invitation_token()
returns text
language plpgsql
as $$
declare
  alphabet text := '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
  alphabet_len int := length(alphabet);
  candidate text;
  attempts int := 0;
begin
  loop
    candidate := '';
    for i in 1..8 loop
      candidate := candidate || substr(alphabet, ceil(random() * alphabet_len)::int, 1);
    end loop;

    if not exists (select 1 from public.guest_group where token = candidate) then
      return candidate;
    end if;

    attempts := attempts + 1;
    if attempts > 10 then
      raise exception 'Could not generate unique invitation token after 10 attempts';
    end if;
  end loop;
end;
$$;

-- =========================================================================
-- 20260509000003_import_function.sql
-- =========================================================================
create or replace function public.import_guest_groups(groups_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  group_data jsonb;
  new_group_id uuid;
  new_token text;
  companion_name text;
  imported jsonb := '[]'::jsonb;
begin
  perform pg_advisory_xact_lock(hashtext('import_guest_groups'));

  for group_data in select * from jsonb_array_elements(groups_data) loop
    new_token := public.generate_invitation_token();

    insert into public.guest_group (
      token, display_name, relationship, max_attendees
    ) values (
      new_token,
      group_data->>'display_name',
      group_data->>'relationship',
      (group_data->>'max_attendees')::int
    )
    returning id into new_group_id;

    insert into public.guest (group_id, full_name, is_primary)
    values (new_group_id, group_data->>'primary_name', true);

    for companion_name in
      select jsonb_array_elements_text(group_data->'companion_names')
    loop
      insert into public.guest (group_id, full_name, is_primary)
      values (new_group_id, companion_name, false);
    end loop;

    imported := imported || jsonb_build_object(
      'group_id', new_group_id,
      'token', new_token,
      'display_name', group_data->>'display_name',
      'relationship', group_data->>'relationship',
      'max_attendees', (group_data->>'max_attendees')::int
    );
  end loop;

  return imported;
end;
$$;

revoke all on function public.import_guest_groups(jsonb) from anon, authenticated;
grant execute on function public.import_guest_groups(jsonb) to service_role;

-- =========================================================================
-- 20260509000004_email_webhook.sql
-- =========================================================================
comment on column public.guest_group.responded_at is
  'Timestamp del primer RSVP. Cambios disparan el database webhook send-rsvp-email.';

-- =========================================================================
-- Seed inicial: admin email
-- =========================================================================
insert into public.admin_users (email)
values ('nicolas.ayalarivas@gmail.com')
on conflict (email) do nothing;

commit;
